language: c

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

install:
  - export CHOOSENIM_CHOOSE_VERSION="stable"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

script:
  - nimble -y test
